feedback.esc.enable:
  type: Integer
  note: 0 - disabled, 1 - enabled with degree publishing, 2 - enabled with quaternion publishing
  enum: PARAM_FEEDBACK_ESC_ENABLE
  flags: mutable
  default: 0
  min: 0
  max: 2

feedback.actuator.enable:
  type: Integer
  note: 0 - disabled, 1 - enabled with degree publishing, 2 - enabled with quaternion publishing
  enum: PARAM_FEEDBACK_ACTUATOR_ENABLE
  flags: mutable
  default: 0
  min: 0
  max: 2

feedback.hardpoint.enable:
  type: Integer
  note: 0 - disabled, 1 - enabled with degree publishing, 2 - enabled with quaternion publishing
  enum: PARAM_FEEDBACK_HARDPOINT_ENABLE
  flags: mutable
  default: 0
  min: 0
  max: 2
