pwm.cmd_ttl_ms:
  type: Integer
  note: TTL of specified by pwm.cmd_type commands [ms].
  enum: PARAM_PWM_CMD_TTL_MS
  flags: mutable
  default: 500
  min: 0
  max: 10000

pwm.frequency:
  type: Integer
  note: PWM frequency [Hz].
  enum: PARAM_PWM_FREQUENCY
  flags: mutable
  default: 50
  min: 50
  max: 400

pwm.cmd_type:
  type: Integer
  note: 0 means RawCommand, 1 means ArrayCommand, 2 is reserved for hardpoint.Command.
  enum: PARAM_PWM_CMD_TYPE
  flags: mutable
  default: 0
  min: 0
  max: 2

pwm1.ch:
  type: Integer
  note: Index of setpoint channel. [-1; 255]. -1 means disabled, # -2 means GPIO SET.
  enum: PARAM_PWM_1_CH
  flags: mutable
  default: -1
  min: -1
  max: 255

pwm1.min:
  type: Integer
  note: PWM duration when setpoint is min (RawCommand is 0 or Command is -1.0)
  enum: PARAM_PWM_1_MIN
  flags: mutable
  default: 1000
  min: 1000
  max: 2000

pwm1.max:
  type: Integer
  note: PWM duration when setpoint is max (RawCommand is 8191 or Command is 1.0)
  enum: PARAM_PWM_1_MAX
  flags: mutable
  default: 2000
  min: 1000
  max: 2000

pwm1.def:
  type: Integer
  note: PWM duration when setpoint is negative or there is no setpoint at all.
  enum: PARAM_PWM_1_DEF
  flags: mutable
  default: 1000
  min: 1000
  max: 2000

pwm2.ch:
  type: Integer
  note: Index of setpoint channel. [-1; 255]. -1 means disabled, # -2 means GPIO SET.
  enum: PARAM_PWM_2_CH
  flags: mutable
  default: -1
  min: -1
  max: 255

pwm2.min:
  type: Integer
  note: PWM duration when setpoint is min (RawCommand is 0 or Command is -1.0)
  enum: PARAM_PWM_2_MIN
  flags: mutable
  default: 1000
  min: 1000
  max: 2000

pwm2.max:
  type: Integer
  note: PWM duration when setpoint is max (RawCommand is 8191 or Command is 1.0)
  enum: PARAM_PWM_2_MAX
  flags: mutable
  default: 2000
  min: 1000
  max: 2000

pwm2.def:
  type: Integer
  note: PWM duration when setpoint is negative or there is no setpoint at all.
  enum: PARAM_PWM_2_DEF
  flags: mutable
  default: 1000
  min: 1000
  max: 2000

pwm3.ch:
  type: Integer
  note: Index of setpoint channel. [-1; 255]. -1 means disabled, # -2 means GPIO SET.
  enum: PARAM_PWM_3_CH
  flags: mutable
  default: -1
  min: -1
  max: 255

pwm3.min:
  type: Integer
  note: PWM duration when setpoint is min (RawCommand is 0 or Command is -1.0)
  enum: PARAM_PWM_3_MIN
  flags: mutable
  default: 1000
  min: 1000
  max: 2000

pwm3.max:
  type: Integer
  note: PWM duration when setpoint is max (RawCommand is 8191 or Command is 1.0)
  enum: PARAM_PWM_3_MAX
  flags: mutable
  default: 2000
  min: 1000
  max: 2000

pwm3.def:
  type: Integer
  note: PWM duration when setpoint is negative or there is no setpoint at all.
  enum: PARAM_PWM_3_DEF
  flags: mutable
  default: 1000
  min: 1000
  max: 2000

pwm4.ch:
  type: Integer
  note: Index of setpoint channel. [-1; 255]. -1 means disabled, # -2 means GPIO SET.
  enum: PARAM_PWM_4_CH
  flags: mutable
  default: -1
  min: -1
  max: 255

pwm4.min:
  type: Integer
  note: PWM duration when setpoint is min (RawCommand is 0 or Command is -1.0)
  enum: PARAM_PWM_4_MIN
  flags: mutable
  default: 1000
  min: 1000
  max: 2000

pwm4.max:
  type: Integer
  note: PWM duration when setpoint is max (RawCommand is 8191 or Command is 1.0)
  enum: PARAM_PWM_4_MAX
  flags: mutable
  default: 2000
  min: 1000
  max: 2000

pwm4.def:
  type: Integer
  note: PWM duration when setpoint is negative or there is no setpoint at all.
  enum: PARAM_PWM_4_DEF
  flags: mutable
  default: 1000
  min: 1000
  max: 2000
