pwm.cmd_ttl_ms:
  type: Integer
  note: TTL of specified by pwm.cmd_type commands [ms].
  enum: PARAM_PWM_CMD_TTL_MS
  flags: mutable
  default: 500
  min: 0
  max: 10000

pwm.frequency:
  type: Integer
  note: PWM frequency [Hz].
  enum: PARAM_PWM_FREQUENCY
  flags: mutable
  default: 50
  min: 50
  max: 400

pwm.cmd_type:
  type: Integer
  note: 0 means RawCommand, 1 means ArrayCommand, 2 is reserved for hardpoint.Command.
  enum: PARAM_PWM_CMD_TYPE
  flags: mutable
  default: 0
  min: 0
  max: 2

pwm.1_ch:
  type: Integer
  note: Index of setpoint channel. [-1; 255]. -1 means disabled, # -2 means GPIO SET.
  enum: PARAM_PWM_1_CH
  flags: mutable
  default: -1
  min: -1
  max: 255

pwm.1_min:
  type: Integer
  note: PWM duration when setpoint is min (RawCommand is 0 or Command is -1.0)
  enum: PARAM_PWM_1_MIN
  flags: mutable
  default: 1000
  min: 1000
  max: 2000

pwm.1_max:
  type: Integer
  note: PWM duration when setpoint is max (RawCommand is 8191 or Command is 1.0)
  enum: PARAM_PWM_1_MAX
  flags: mutable
  default: 2000
  min: 1000
  max: 2000

pwm.1_def:
  type: Integer
  note: PWM duration when setpoint is negative or there is no setpoint at all.
  enum: PARAM_PWM_1_DEF
  flags: mutable
  default: 1000
  min: 1000
  max: 2000

pwm.2_ch:
  type: Integer
  note: Index of setpoint channel. [-1; 255]. -1 means disabled, # -2 means GPIO SET.
  enum: PARAM_PWM_2_CH
  flags: mutable
  default: -1
  min: -1
  max: 255

pwm.2_min:
  type: Integer
  note: PWM duration when setpoint is min (RawCommand is 0 or Command is -1.0)
  enum: PARAM_PWM_2_MIN
  flags: mutable
  default: 1000
  min: 1000
  max: 2000

pwm.2_max:
  type: Integer
  note: PWM duration when setpoint is max (RawCommand is 8191 or Command is 1.0)
  enum: PARAM_PWM_2_MAX
  flags: mutable
  default: 2000
  min: 1000
  max: 2000

pwm.2_def:
  type: Integer
  note: PWM duration when setpoint is negative or there is no setpoint at all.
  enum: PARAM_PWM_2_DEF
  flags: mutable
  default: 1000
  min: 1000
  max: 2000

pwm.3_ch:
  type: Integer
  note: Index of setpoint channel. [-1; 255]. -1 means disabled, # -2 means GPIO SET.
  enum: PARAM_PWM_3_CH
  flags: mutable
  default: -1
  min: -1
  max: 255

pwm.3_min:
  type: Integer
  note: PWM duration when setpoint is min (RawCommand is 0 or Command is -1.0)
  enum: PARAM_PWM_3_MIN
  flags: mutable
  default: 1000
  min: 1000
  max: 2000

pwm.3_max:
  type: Integer
  note: PWM duration when setpoint is max (RawCommand is 8191 or Command is 1.0)
  enum: PARAM_PWM_3_MAX
  flags: mutable
  default: 2000
  min: 1000
  max: 2000

pwm.3_def:
  type: Integer
  note: PWM duration when setpoint is negative or there is no setpoint at all.
  enum: PARAM_PWM_3_DEF
  flags: mutable
  default: 1000
  min: 1000
  max: 2000

pwm.4_ch:
  type: Integer
  note: Index of setpoint channel. [-1; 255]. -1 means disabled, # -2 means GPIO SET.
  enum: PARAM_PWM_4_CH
  flags: mutable
  default: -1
  min: -1
  max: 255

pwm.4_min:
  type: Integer
  note: PWM duration when setpoint is min (RawCommand is 0 or Command is -1.0)
  enum: PARAM_PWM_4_MIN
  flags: mutable
  default: 1000
  min: 1000
  max: 2000

pwm.4_max:
  type: Integer
  note: PWM duration when setpoint is max (RawCommand is 8191 or Command is 1.0)
  enum: PARAM_PWM_4_MAX
  flags: mutable
  default: 2000
  min: 1000
  max: 2000

pwm.4_def:
  type: Integer
  note: PWM duration when setpoint is negative or there is no setpoint at all.
  enum: PARAM_PWM_4_DEF
  flags: mutable
  default: 1000
  min: 1000
  max: 2000
