uavcan.pub.udral_feedback1:
  type: Port
  data_type: reg.udral.service.actuator.common.Feedback.0.1
  enum_base: PARAM_PUB_FEEDBACK_1

uavcan.pub.udral_feedback2:
  type: Port
  data_type: reg.udral.service.actuator.common.Feedback.0.1
  enum_base: PARAM_PUB_FEEDBACK_2

uavcan.pub.udral_feedback3:
  type: Port
  data_type: reg.udral.service.actuator.common.Feedback.0.1
  enum_base: PARAM_PUB_FEEDBACK_3

uavcan.pub.udral_feedback4:
  type: Port
  data_type: reg.udral.service.actuator.common.Feedback.0.1
  enum_base: PARAM_PUB_FEEDBACK_4

uavcan.pub.zubax_feedback1:
  type: Port
  data_type: zubax.telega.CompactFeedback.0.1
  enum_base: PARAM_PUB_COMPACT_FEEDBACK_1

uavcan.pub.zubax_feedback2:
  type: Port
  data_type: zubax.telega.CompactFeedback.0.1
  enum_base: PARAM_PUB_COMPACT_FEEDBACK_2

uavcan.pub.zubax_feedback3:
  type: Port
  data_type: zubax.telega.CompactFeedback.0.1
  enum_base: PARAM_PUB_COMPACT_FEEDBACK_3

uavcan.pub.zubax_feedback4:
  type: Port
  data_type: zubax.telega.CompactFeedback.0.1
  enum_base: PARAM_PUB_COMPACT_FEEDBACK_4
