uavcan.node.id:
  type: Integer
  note: Defines a node-ID. Allowed values [0,127].
  enum: PARAM_UAVCAN_NODE_ID
  flags: mutable
  default: 42
  min: 0
  max: 255

uavcan.node.description:
  note: User/integrator-defined, human-readable description of this specific node.
  type: String
  enum: PARAM_NODE_DESCRIPTION
  flags: mutable
  default: ""

system.can_terminator:
  type: Integer
  note: Bitmask which switch can terminators (0 - both off, 1 - enables second, 2 - enables first, 3 - enables both). Works only for v3.
  enum: PARAM_SYSTEM_CAN_TEMINATOR
  flags: mutable
  default: 0
  min: 0
  max: 3

system.name:
  type: String
  note: Defines custom node name. If empty, the node will use the default name.
  enum: PARAM_SYSTEM_NAME
  flags: mutable
  default: "co.raccoonlab.mini"

system.protocol:
  type: Integer
  note: Auto, Cyphal/CAN or DroneCAN
  enum: PARAM_SYSTEM_PROTOCOL
  flags: mutable
  default: 0
  min: 0
  max: 2

system.log_level:
  type: Integer
  note:
    "Log level. See [debug.LogLevel](https://dronecan.github.io/Specification/7._List_of_standard_data_types/#loglevel) and [diagnostic.Severity](https://github.com/OpenCyphal/public_regulated_data_types/blob/master/uavcan/diagnostic/Severity.1.0.dsdl).
    </br> 0 - Log everything (DEBUG, INFO, WARNING, ERROR)
    </br> 1 - Log at least INFO level
    </br> 2 - Log at least WARNING level
    </br> 3 - Log at least ERROR level
    </br> 4 - Disable logging
    </br> By default 3 to show only realy important messages."
  enum: PARAM_LOG_LEVEL
  flags: mutable
  default: 3
  min: 0
  max: 4
