example.integer:
  type: Integer
  note: Just an integer register example
  enum: PARAM_EXAMPLE_INTEGER
  flags: mutable
  default: 42
  min: 0
  max: 255

example.string:
  type: String
  note: Just a string register example
  enum: PARAM_EXAMPLE_STRING
  flags: mutable
  default: "default_string_value"
