pwm.input_type:
  type: Integer
  note: 0 means RawCommand, 1 means ArrayCommand, 2 is reserved for hardpoint.Command.
  enum: PARAM_PWM_INPUT_TYPE
  flags: mutable
  default: 0
  min: 0
  max: 2
  
servo.max_travel_degrees:
  type: Integer
  note: Maximum angular travel from PWM minimum to maximum (degrees).
  enum: PARAM_SERVO_MAX_TRAVEL_DEG
  flags: mutable
  default: 90
  min: 0
  max: 360
  
gimbal.id:
  type: Integer
  note: Current gimbal ID (to account several gimbals connected to one bus).
  enum: PARAM_GIMBAL_ID
  flags: mutable
  default: 0
  min: 0
  max: 127