# This is a short form that generates Integer & String registers related to the subscriber with PORT_NAME=feedback:
# - Integer register with name `uavcan.pub.feedback.id`
# - String register with name `uavcan.pub.feedback.type`
# The generated registers have proper flags, data type and min, max and default values.
# They correspond the standard: https://github.com/OpenCyphal/public_regulated_data_types/blob/master/uavcan/register/384.Access.1.0.dsdl
uavcan.pub.feedback:
  type: Port
  data_type: reg.udral.service.actuator.common.Feedback.0.1
  enum_base: PARAM_PUB_FEEDBACK_1
