# Copyright (C) 2023-2024 Dmitry Ponomarev <ponomarevda96@gmail.com>
# Distributed under the terms of the GPL v3 license, available in the file LICENSE.

# create_binary_with_meaningful_name.cmake

# Ensure the required variables are defined
if(NOT DEFINED BUILD_OBJ_DIR OR NOT DEFINED PROJECT_NAME OR
   NOT DEFINED BOARD_VENDOR OR NOT DEFINED BOARD_NAME)
    message(FATAL_ERROR "BUILD_OBJ_DIR, PROJECT_NAME, BOARD_VENDOR and BOARD_NAME must be defined")
endif()

set(SOURCE_BIN "${BUILD_OBJ_DIR}/example.bin")
# message(FATAL_ERROR "${SOURCE_BIN}")

# Define the source and destination paths.
if(DEFINED NC_RELEASE_DIR AND NOT NC_RELEASE_DIR STREQUAL "")
    set(DESTINATION_DIR "${NC_RELEASE_DIR}")
elseif(DEFINED NC_RELEASE_APP_ROOT_DIR AND NOT NC_RELEASE_APP_ROOT_DIR STREQUAL "")
    set(DESTINATION_DIR "${NC_RELEASE_APP_ROOT_DIR}/release")
elseif(DEFINED NC_APP_SRC_DIR AND NOT NC_APP_SRC_DIR STREQUAL "")
    get_filename_component(APP_ROOT_DIR "${NC_APP_SRC_DIR}" DIRECTORY)
    set(DESTINATION_DIR "${APP_ROOT_DIR}/release")
else()
    set(DESTINATION_DIR "${BUILD_ROOT_DIR}/release")
endif()

if(DEFINED NC_RELEASE_APP_ROOT_DIR AND NOT NC_RELEASE_APP_ROOT_DIR STREQUAL "")
    set(RELEASE_APP_ROOT_DIR "${NC_RELEASE_APP_ROOT_DIR}")
elseif(DEFINED NC_APP_SRC_DIR AND NOT NC_APP_SRC_DIR STREQUAL "")
    get_filename_component(RELEASE_APP_ROOT_DIR "${NC_APP_SRC_DIR}" DIRECTORY)
else()
    set(RELEASE_APP_ROOT_DIR "")
endif()

set(RELEASE_BOARD_NAME "${BOARD_NAME}")
if(DEFINED NC_TARGET AND NOT NC_TARGET STREQUAL "" AND
   NOT NC_TARGET STREQUAL "default" AND
   NOT NC_TARGET STREQUAL CAN_PROTOCOL)
    set(RELEASE_BOARD_NAME "${BOARD_NAME}_${NC_TARGET}")
endif()

set(RELEASE_HW_VERSION "${PLATFORM_NAME}")
if(NOT DEFINED RELEASE_HW_VERSION OR RELEASE_HW_VERSION STREQUAL "")
    set(RELEASE_HW_VERSION "unknown")
endif()

set(RELEASE_FW_TYPE "${IMAGE_KIND}")
if(NOT DEFINED RELEASE_FW_TYPE OR RELEASE_FW_TYPE STREQUAL "")
    set(RELEASE_FW_TYPE "standalone")
endif()

set(RELEASE_COMMIT_HASH "${GIT_HASH_SHORT_8_DIGITS}")
if(NOT RELEASE_APP_ROOT_DIR STREQUAL "" AND EXISTS "${RELEASE_APP_ROOT_DIR}/.git")
    execute_process(
        COMMAND git rev-parse --short=8 HEAD
        WORKING_DIRECTORY "${RELEASE_APP_ROOT_DIR}"
        RESULT_VARIABLE RELEASE_APP_GIT_HASH_RESULT
        OUTPUT_VARIABLE RELEASE_APP_GIT_HASH
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    if(RELEASE_APP_GIT_HASH_RESULT EQUAL 0 AND NOT RELEASE_APP_GIT_HASH STREQUAL "")
        set(RELEASE_COMMIT_HASH "${RELEASE_APP_GIT_HASH}")
    endif()
endif()

if(NOT DEFINED RELEASE_FW_VERSION OR RELEASE_FW_VERSION STREQUAL "")
    execute_process(
        COMMAND git describe --tags --abbrev=0 --match "v*"
        WORKING_DIRECTORY "${ROOT_DIR}"
        RESULT_VARIABLE RELEASE_NODE_CORE_TAG_RESULT
        OUTPUT_VARIABLE RELEASE_NODE_CORE_TAG
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )

    set(RELEASE_APP_TAG_RESULT 1)
    set(RELEASE_APP_TAG "")
    if(NOT RELEASE_APP_ROOT_DIR STREQUAL "" AND EXISTS "${RELEASE_APP_ROOT_DIR}/.git")
        execute_process(
            COMMAND git describe --tags --abbrev=0 --match "v*"
            WORKING_DIRECTORY "${RELEASE_APP_ROOT_DIR}"
            RESULT_VARIABLE RELEASE_APP_TAG_RESULT
            OUTPUT_VARIABLE RELEASE_APP_TAG
            ERROR_QUIET
            OUTPUT_STRIP_TRAILING_WHITESPACE
        )
    endif()

    if(NOT RELEASE_NODE_CORE_TAG_RESULT EQUAL 0 OR RELEASE_NODE_CORE_TAG STREQUAL "")
        set(RELEASE_NODE_CORE_TAG "v${APP_VERSION_MAJOR}.${APP_VERSION_MINOR}.${APP_VERSION_PATCH}")
    endif()

    if(RELEASE_APP_TAG_RESULT EQUAL 0 AND NOT RELEASE_APP_TAG STREQUAL "")
        string(REGEX REPLACE "^v" "" RELEASE_APP_TAG_SUFFIX "${RELEASE_APP_TAG}")
        set(RELEASE_FW_VERSION "${RELEASE_NODE_CORE_TAG}-${RELEASE_APP_TAG_SUFFIX}")
    else()
        set(RELEASE_FW_VERSION "${RELEASE_NODE_CORE_TAG}")
    endif()
endif()

string(TIMESTAMP RELEASE_DATE "%Y.%m.%d")
set(DESTINATION_BIN "${DESTINATION_DIR}/${BOARD_VENDOR}_${RELEASE_BOARD_NAME}_${RELEASE_HW_VERSION}_${RELEASE_FW_TYPE}_${RELEASE_FW_VERSION}_${RELEASE_DATE}_${RELEASE_COMMIT_HASH}.bin")

# Create the release directory if it doesn't exist
file(MAKE_DIRECTORY "${DESTINATION_DIR}")

if(NOT DEFINED FIRMWARE_FINAL_TARGET OR FIRMWARE_FINAL_TARGET STREQUAL "")
    set(FIRMWARE_FINAL_TARGET ${EXECUTABLE})
endif()

set(RELEASE_COPY_TARGET "${EXECUTABLE}_release_bin")

add_custom_command(
    OUTPUT ${DESTINATION_BIN}
    COMMAND ${CMAKE_COMMAND} -E make_directory ${DESTINATION_DIR}
    COMMAND ${CMAKE_COMMAND} -E copy ${BUILD_OBJ_DIR}/${PROJECT_NAME}.bin ${DESTINATION_BIN}
    DEPENDS
        ${FIRMWARE_FINAL_TARGET}
        ${BUILD_OBJ_DIR}/${PROJECT_NAME}.bin
    COMMENT "Copying release binary"
    VERBATIM
)

add_custom_target(${RELEASE_COPY_TARGET} ALL DEPENDS ${DESTINATION_BIN})
add_dependencies(${RELEASE_COPY_TARGET} ${FIRMWARE_FINAL_TARGET})
