# Copyright (C) 2023-2024 Dmitry Ponomarev <ponomarevda96@gmail.com>
# Distributed under the terms of the GPL v3 license, available in the file LICENSE.

if(NOT CMAKE_CXX_COMPILER_ID)
    message(FATAL_ERROR "C++ compiler not set yet")
endif()
set(TOOLCHAIN_INFO "${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
add_definitions(-DFIRMWARE_FULL_INFO="Node v${APP_VERSION_MAJOR}.${APP_VERSION_MINOR}.${APP_VERSION_PATCH}_${GIT_HASH_SHORT_8_DIGITS} ${CMAKE_BUILD_TYPE} ${TOOLCHAIN_INFO}")

string(TIMESTAMP BUILD_TIMESTAMP_UTC "%s" UTC)

set(RELEASE_BUILD_FLAG 1)
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(RELEASE_BUILD_FLAG 0)
endif()

execute_process(
    COMMAND git status --porcelain
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_STATUS_PORCELAIN
    OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(DIRTY_BUILD_FLAG 0)
if(NOT "${GIT_STATUS_PORCELAIN}" STREQUAL "")
    set(DIRTY_BUILD_FLAG 1)
endif()
