imu.publishers:
  type: Integer
  note: 
      "Bit mask to enable IMU publishers:
    </br> Bit 1 - enable RawImu publisher,
    </br> Bit 2 - enable vibration metric publishing to RawImu.integration_interval,
    </br> Bit 3 - enable FFT acceleration publishing to RawImu.accelerometer_integral,
    </br> Bit 4 - enable FFT acceleration publishing to RawImu.rate_gyro_integral,
    </br> 15 - enable all publishers"
  enum: PARAM_IMU_PUBLISHERS_BITMASK
  flags: mutable
  default: 0
  min: 0
  max: 15

imu.data_source:
  type: Integer
  note: 
      "Values to enable IMU data source readings:
    </br> 0 - use nothing,
    </br> 1 - enable synthetic data generation,
    </br> 2 - use FIFO for real data readings (sample rate = 100Hz, Bandwidth (gyro/accel) = 41/~44.8Hz),
    </br> 3 - use forward register adressing for data readings."
  enum: PARAM_IMU_DATA_SOURCE
  flags: mutable
  default: 0
  min: 0
  max: 3

imu.pub_frequency:
  type: Integer
  note: Frequency of IMU publisher [Hz].
  enum: PARAM_IMU_PUB_FREQUENCY
  flags: mutable
  default: 1
  min: 0
  max: 256

imu.synthetic_frequency:
  type: Integer
  note: "Set frequency for synthetic oscilation generation on OX axis acceleration. 
    </br> If you want higher frequency then need to update FFT and other generation params to avoid aliasing."
  enum: SYNTHETIC_FREQ_GEN
  flags: mutable
  default: 8
  min: 1
  max: 128

imu.synthetic_amplitude:
  type: Integer
  note: "Set ampliture for synthetic oscilation generation on OX axis acceleration."
  enum: SYNTHETIC_AMPLITUDE
  flags: mutable
  default: 20
  min: 1
  max: 1000
