name: build_cyphal
on: [push]
jobs:
  build_cyphal:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: ./scripts/tools/install_for_ubuntu.sh --yes

      - run: make generate_dsdl
      - run: make cyphal

      - name: Archive .bin file
        uses: actions/upload-artifact@v3
        with:
          name: cyphal_firmware.bin
          path: build/obj/example.bin

      - name: Archive .elf file
        uses: actions/upload-artifact@v3
        with:
          name: cyphal_firmware.elf
          path: build/obj/example.elf
