name: code_style

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'

jobs:
  cpplint:
    timeout-minutes: 1
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install cpplint
      - name: cpplint
        run: |
          make code_style
