name: cyphal
on: [push]
jobs:
  stm32f103:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: ./scripts/tools/install_for_ubuntu.sh --yes

      - name: Archive .bin file
        uses: actions/upload-artifact@v3
        with:
          name: cyphal_firmware.bin
          path: build/obj/example.bin

      - name: Archive .elf file
        uses: actions/upload-artifact@v3
        with:
          name: cyphal_firmware.elf
          path: build/obj/example.elf

  sitl:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: |
          ./scripts/tools/install_for_ubuntu.sh --yes
          pip install pytest
      - run: make sitl_cyphal
      - run: |
          export REG_DATA_TYPE_PATH="$PWD/Libs/Cyphal/Libs/public_regulated_data_types/uavcan $PWD/Libs/Cyphal/Libs/public_regulated_data_types/reg"
          make run &
          cd scripts/tools/cyphal
          source init.sh -i slcan0 -n 127 -v
          ./specification_checker.py
