name: cyphal
on: [push]
jobs:
  stm32f103:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: |
          pip install pyserial python-can pydronecan pycyphal pytest pytest-asyncio yakut
          pip install -i https://test.pypi.org/simple/ raccoonlab-tools
          pip install -U nunavut
          sudo apt-get install -y gcc-arm-none-eabi stlink-tools

      - run: make cyphal

      - name: Archive .bin file
        uses: actions/upload-artifact@v3
        with:
          name: cyphal_firmware.bin
          path: build/obj/example.bin
          if-no-files-found: error

      - name: Archive .elf file
        uses: actions/upload-artifact@v3
        with:
          name: cyphal_firmware.elf
          path: build/obj/example.elf
          if-no-files-found: error

  sitl:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Clone Cyphal DSDL
        run: |
          mkdir -p /home/runner/.cyphal/zubax_dsdl
          git clone https://github.com/Zubax/zubax_dsdl.git /home/runner/.cyphal/zubax_dsdl

          mkdir -p /home/runner/.cyphal/public_regulated_data_types
          git clone https://github.com/OpenCyphal/public_regulated_data_types.git /home/runner/.cyphal/public_regulated_data_types

      - name: Install dependencies
        run: |
          pip install pyserial python-can pydronecan pycyphal pytest pytest-asyncio yakut
          pip install -i https://test.pypi.org/simple/ raccoonlab-tools
          pip install -U nunavut
          sudo apt-get install -y linux-modules-extra-$(uname -r)

      - run: make sitl_cyphal
      - run: |
          make run &
          cd scripts/tools/scripts/cyphal
          source init.sh -i slcan0 -n 127 -v
          rl-test-cyphal-specification -k "not test_unique_id"
