name: dronecan
on: [push]
jobs:
  stm32f103:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          repository: PonomarevDA/dronecan_application
          path: 'Libs/Dronecan'
          token: ${{ secrets.DRONECAN_APPLICATION_TOKEN }}
          fetch-depth: 0
      - name: Checkout Dronecan
        run: cd Libs/Dronecan && git checkout bb50fad # v0.3.1

      - name: Inscripts/tools/stall dependencies
        run: |
          sudo apt-get install -y gcc-arm-none-eabi stlink-tools

      - run: make dronecan

  sitl:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          repository: PonomarevDA/dronecan_application
          path: 'Libs/Dronecan'
          token: ${{ secrets.DRONECAN_APPLICATION_TOKEN }}
          fetch-depth: 0
      - name: Checkout Dronecan
        run: cd Libs/Dronecan && git checkout bb50fad # v0.3.1

      - name: Install dependencies
        run: |
          pip install pyserial python-can pydronecan pycyphal pytest pytest-asyncio yakut
          pip install -i https://test.pypi.org/simple/ raccoonlab-tools
          sudo apt-get install -y linux-modules-extra-$(uname -r)

      - run: make sitl_dronecan
      - run: |
          make run &
          rl-test-dronecan-specification
