# Copyright (C) 2026 Dmitry Ponomarev <ponomarevda96@gmail.com>
# Distributed under the terms of the GPL v3 license, available in the file LICENSE.

set(BOARD_PLATFORM stm32f103)
set(STM32_CUBEMX_PROJECT_PATH ${ROOT_DIR}/Libs/stm32-cube-project)
set(CAN_PROTOCOL both)
if(NOT DEFINED IMAGE_KIND OR IMAGE_KIND STREQUAL "")
    set(IMAGE_KIND standalone)
endif()
if(NOT IMAGE_KIND STREQUAL "standalone" AND NOT IMAGE_KIND STREQUAL "application")
    message(FATAL_ERROR "IMAGE_KIND must be standalone or application, got '${IMAGE_KIND}'")
endif()

set(STM32_LINKER_SCRIPT_TEMPLATE_PATH ${CMAKE_CURRENT_LIST_DIR}/STM32F103T8UX_FLASH.ld.in)
set(BOARD_FLASH_ORIGIN_HEX 0x08000000)
set(BOARD_FLASH_SIZE_KB 128)
set(BOOTLOADER_RESERVED_KB 32)
if(IMAGE_KIND STREQUAL "standalone")
    set(LINK_FLASH_ORIGIN_HEX ${BOARD_FLASH_ORIGIN_HEX})
    set(LINK_FLASH_LENGTH_KB ${BOARD_FLASH_SIZE_KB})
else()
    math(EXPR APP_FLASH_ORIGIN_DEC "0x08000000 + ${BOOTLOADER_RESERVED_KB} * 1024")
    set(LINK_FLASH_ORIGIN_HEX ${APP_FLASH_ORIGIN_DEC})
    math(EXPR LINK_FLASH_LENGTH_KB "${BOARD_FLASH_SIZE_KB} - ${BOOTLOADER_RESERVED_KB}")
endif()
if(BOARD_CONFIG_ONLY)
    return()
endif()
include(${CMAKE_CURRENT_LIST_DIR}/cyphal.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/dronecan.cmake)
